#!/usr/bin/env bash

interface=$1
event=$2

if [[ $interface == "end0" ]]
then
    if [[ $event == "up" ]]
    then
        ip route replace blackhole 1.1.1.1/32
        ip route replace blackhole 1.0.0.1/32
    fi
fi
